### ISSUE TITLE
Golang packages (eg: golang.org/x/net) should use current golang git repos

### ISSUE THREAD

**Issue by jprjr** [gpmgo/switch#4]
It looks like switch is pulling down old code Google Code - those repos haven't been updated since December 2014.

The current repos are at https://go.googlesource.com/

**Comment by Unknwon** [comment]
Thanks @jprjr , good catch!

Did some digging and it looks like source code on GitHub is up-to-date, so I can change it to download source from GitHub.

**Comment by Unknwon** [comment]
Hi! I've pushed code and updated gopm.io as well. It is now fetching code from GitHub.
